# Generated by Django 4.0 on 2022-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_homework_options_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=15)),
                ('sinif', models.CharField(max_length=7)),
                ('pdfyol', models.FileField(upload_to='static/pdf')),
            ],
        ),
    ]
