# Generated by Django 4.0 on 2022-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='ders',
            field=models.CharField(max_length=30),
        ),
    ]
