# Generated by Django 4.0 on 2022-01-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_pdf_ders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
