# Generated by Django 4.0 on 2022-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=30)),
                ('sinif', models.CharField(max_length=7)),
                ('owner', models.CharField(default='', max_length=100)),
                ('pdf', models.FileField(upload_to='static/pdfs/')),
                ('kapak', models.ImageField(default='', upload_to='static/kapaklar/')),
            ],
        ),
    ]
