# Generated by Django 4.0 on 2022-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='kapak',
            field=models.ImageField(default='', null=True, upload_to='static/kapaklar/'),
        ),
    ]
