# Generated by Django 4.0 on 2022-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_pdf_kapak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='kapak',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/kapaklar/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
