# Generated by Django 4.0 on 2022-01-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_pdf_kapak_alter_pdf_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='owner',
        ),
    ]
